# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main2.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class StringBox(QtWidgets.QSpinBox):
    def __init__(self, parent=None, options=None):
        super(StringBox, self).__init__(parent)

        self.setStrings(options)

        print('lol keke')

    def setStrings(self, strings):
        strings = list(strings)
        self._strings = tuple(strings)
        self.values = dict(zip(strings, range(len(strings))))
        self.setRange(0, len(strings)-1)

    def textFromValue(self, value):
        return self._strings[value]


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(820, 667)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.change_btn = QtWidgets.QPushButton(self.centralwidget)
        self.change_btn.setGeometry(QtCore.QRect(640, 210, 161, 23))
        self.change_btn.setObjectName("change_btn")
        self.description = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.description.setGeometry(QtCore.QRect(420, 80, 211, 181))
        self.description.setObjectName("description")
        self.status_inp = StringBox(
            self.centralwidget, ['В процессе', 'Отложено', 'Завершено']
        )
        self.status_inp.setGeometry(QtCore.QRect(640, 150, 161, 21))
        self.status_inp.setObjectName("status_inp")
        self.name = QtWidgets.QLineEdit(self.centralwidget)
        self.name.setGeometry(QtCore.QRect(420, 50, 381, 20))
        self.name.setObjectName("name")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(580, 10, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semilight")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setLineWidth(10)
        self.label.setObjectName("label")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 140, 381, 471))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.tasks_layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.tasks_layout.setContentsMargins(0, 0, 0, 0)
        self.tasks_layout.setObjectName("tasks_layout")
        self.category_select = StringBox(
            self.centralwidget, ['Работа', 'Школа', 'Отдых']
        )
        self.category_select.setGeometry(QtCore.QRect(80, 50, 321, 22))
        self.category_select.setObjectName("category_select")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(150, 10, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semilight")
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setLineWidth(10)
        self.label_2.setObjectName("label_2")
        self.datetime = QtWidgets.QDateTimeEdit(self.centralwidget)
        self.datetime.setGeometry(QtCore.QRect(640, 180, 161, 22))
        self.datetime.setObjectName("datetime")
        self.category_inp = StringBox(
            self.centralwidget, ['Работа', 'Школа', 'Отдых']
        )
        self.category_inp.setGeometry(QtCore.QRect(640, 100, 161, 22))
        self.category_inp.setObjectName("category_inp")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 50, 61, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 80, 61, 16))
        self.label_4.setObjectName("label_4")
        self.status_select = StringBox(
            self.centralwidget, ['В процессе', 'Отложено', 'Завершено']
        )
        self.status_select.setGeometry(QtCore.QRect(80, 80, 321, 22))
        self.status_select.setObjectName("status_select")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(680, 80, 61, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(690, 130, 61, 16))
        self.label_6.setObjectName("label_6")
        self.find_tasks_btn = QtWidgets.QPushButton(self.centralwidget)
        self.find_tasks_btn.setGeometry(QtCore.QRect(20, 110, 379, 23))
        self.find_tasks_btn.setObjectName("find_tasks_btn")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(380, 620, 21, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(20, 620, 21, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.new_task_btn = QtWidgets.QPushButton(self.centralwidget)
        self.new_task_btn.setGeometry(QtCore.QRect(640, 240, 161, 23))
        self.new_task_btn.setObjectName("new_task_btn")
        self.category_name_inp = QtWidgets.QLineEdit(self.centralwidget)
        self.category_name_inp.setGeometry(QtCore.QRect(420, 310, 381, 20))
        self.category_name_inp.setObjectName("category_name_inp")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(560, 270, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semilight")
        font.setPointSize(16)
        self.label_8.setFont(font)
        self.label_8.setLineWidth(10)
        self.label_8.setObjectName("label_8")
        self.new_category_btn = QtWidgets.QPushButton(self.centralwidget)
        self.new_category_btn.setGeometry(QtCore.QRect(420, 340, 381, 23))
        self.new_category_btn.setObjectName("new_category_btn")
        self.status_name_inp = QtWidgets.QLineEdit(self.centralwidget)
        self.status_name_inp.setGeometry(QtCore.QRect(420, 500, 381, 20))
        self.status_name_inp.setObjectName("status_name_inp")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(570, 460, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semilight")
        font.setPointSize(16)
        self.label_9.setFont(font)
        self.label_9.setLineWidth(10)
        self.label_9.setObjectName("label_9")
        self.new_category_btn_2 = QtWidgets.QPushButton(self.centralwidget)
        self.new_category_btn_2.setGeometry(QtCore.QRect(420, 530, 381, 23))
        self.new_category_btn_2.setObjectName("new_category_btn_2")
        self.category_scroll = QtWidgets.QScrollArea(self.centralwidget)
        self.category_scroll.setGeometry(QtCore.QRect(420, 370, 381, 80))
        self.category_scroll.setWidgetResizable(True)
        self.category_scroll.setObjectName("category_scroll")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 379, 78))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.horizontalLayoutWidget = QtWidgets.QWidget(
            self.scrollAreaWidgetContents)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 381, 33))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.hboxlayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.hboxlayout.setContentsMargins(5, 5, 5, 5)
        self.hboxlayout.setObjectName("hboxlayout")
        self.pushButton_7 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_7.setText("")
        self.pushButton_7.setObjectName("pushButton_7")
        self.hboxlayout.addWidget(self.pushButton_7)
        self.pushButton_8 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_8.setObjectName("pushButton_8")
        self.hboxlayout.addWidget(self.pushButton_8)
        self.category_scroll.setWidget(self.scrollAreaWidgetContents)
        self.status_scroll = QtWidgets.QScrollArea(self.centralwidget)
        self.status_scroll.setGeometry(QtCore.QRect(420, 560, 381, 80))
        self.status_scroll.setWidgetResizable(True)
        self.status_scroll.setObjectName("status_scroll")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(
            QtCore.QRect(0, 0, 379, 78))
        self.scrollAreaWidgetContents_2.setObjectName(
            "scrollAreaWidgetContents_2")
        self.status_scroll.setWidget(self.scrollAreaWidgetContents_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.change_btn.setText(_translate("MainWindow", "Создать / Изменить"))
        self.description.setPlainText(
            _translate("MainWindow", "Описание задачи"))
        self.name.setText(_translate("MainWindow", "Название задачи"))
        self.label.setText(_translate("MainWindow", "Задача"))
        self.label_2.setText(_translate("MainWindow", "Выбор задачи"))
        self.label_3.setText(_translate("MainWindow", "Категория"))
        self.label_4.setText(_translate("MainWindow", "Статус"))
        self.label_5.setText(_translate("MainWindow", "Категория"))
        self.label_6.setText(_translate("MainWindow", "Статус"))
        self.find_tasks_btn.setText(_translate("MainWindow", "Найти"))
        self.pushButton_2.setText(_translate("MainWindow", ">"))
        self.pushButton_3.setText(_translate("MainWindow", "<"))
        self.new_task_btn.setText(_translate("MainWindow", "Новая задача"))
        self.category_name_inp.setText(
            _translate("MainWindow", "Название категории"))
        self.label_8.setText(_translate("MainWindow", "Категории"))
        self.new_category_btn.setText(
            _translate("MainWindow", "Новая категория"))
        self.status_name_inp.setText(
            _translate("MainWindow", "Название статуса"))
        self.label_9.setText(_translate("MainWindow", "Статусы"))
        self.new_category_btn_2.setText(
            _translate("MainWindow", "Создать статус"))
        self.pushButton_8.setText(_translate("MainWindow", "Удалить"))
