# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class StringBox(QtWidgets.QSpinBox):
    def __init__(self, parent=None, options=None):
        super(StringBox, self).__init__(parent)

        self.setStrings(options)

        print('lol keke')

    def setStrings(self, strings):
        strings = list(strings)
        self._strings = tuple(strings)
        self.values = dict(zip(strings, range(len(strings))))
        self.setRange(0, len(strings)-1)

    def textFromValue(self, value):
        return self._strings[value]


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(424, 466)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.change_btn = QtWidgets.QPushButton(self.centralwidget)
        self.change_btn.setGeometry(QtCore.QRect(240, 420, 161, 23))
        self.change_btn.setObjectName("change_btn")
        self.search_btn = QtWidgets.QPushButton(self.centralwidget)
        self.search_btn.setGeometry(QtCore.QRect(20, 20, 100, 23))
        self.search_btn.setObjectName("search_btn")
        self.description = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.description.setGeometry(QtCore.QRect(20, 290, 211, 151))
        self.description.setObjectName("description")
        self.status_inp = StringBox(
            self.centralwidget, ['В процессе', 'Отложено', 'Завершено']
        )
        self.status_inp.setGeometry(QtCore.QRect(240, 360, 161, 21))
        self.status_inp.setObjectName("status_inp")
        self.name = QtWidgets.QLineEdit(self.centralwidget)
        self.name.setGeometry(QtCore.QRect(20, 260, 381, 20))
        self.name.setObjectName("name")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(170, 220, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semilight")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setLineWidth(10)
        self.label.setObjectName("label")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 120, 381, 101))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.tasks_layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.tasks_layout.setContentsMargins(0, 0, 0, 0)
        self.tasks_layout.setObjectName("tasks_layout")
        self.category_select = StringBox(
            self.centralwidget, ['Работа', 'Школа', 'Отдых']
        )
        self.category_select.setGeometry(QtCore.QRect(80, 50, 321, 22))
        self.category_select.setObjectName("category_select")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(150, 10, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semilight")
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setLineWidth(10)
        self.label_2.setObjectName("label_2")
        self.datetime = QtWidgets.QDateTimeEdit(self.centralwidget)
        self.datetime.setGeometry(QtCore.QRect(240, 390, 161, 22))
        self.datetime.setObjectName("datetime")
        self.category_inp = StringBox(
            self.centralwidget, ['Работа', 'Школа', 'Отдых']
        )
        self.category_inp.setGeometry(QtCore.QRect(240, 310, 161, 22))
        self.category_inp.setObjectName("category_inp")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 50, 61, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 80, 61, 16))
        self.label_4.setObjectName("label_4")
        self.status_select = StringBox(
            self.centralwidget, ['В процессе', 'Отложено', 'Завершено']
        )
        self.status_select.setGeometry(QtCore.QRect(80, 80, 321, 22))
        self.status_select.setObjectName("status_select")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(280, 290, 61, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(290, 340, 61, 16))
        self.label_6.setObjectName("label_6")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.change_btn.setText(_translate("MainWindow", "Создать / Изменить"))
        self.search_btn.setText(_translate("MainWindow", "Найти"))
        self.description.setPlainText(
            _translate("MainWindow", "Описание задачи"))
        self.name.setText(_translate("MainWindow", "Название задачи"))
        self.label.setText(_translate("MainWindow", "О задачe"))
        self.label_2.setText(_translate("MainWindow", "Выбор задачи"))
        self.label_3.setText(_translate("MainWindow", "Категория"))
        self.label_4.setText(_translate("MainWindow", "Статус"))
        self.label_5.setText(_translate("MainWindow", "Категория"))
        self.label_6.setText(_translate("MainWindow", "Статус"))
